### ISSUE TITLE
Incorrect display of text on phones.

### ISSUE THREAD

**Issue by Pelfox** [Discordoo/discordoo-website#1]
Hello.

### What’s wrong?
When I go to your website on my phone, the text in the header block is almost impossible to read (after all, some letters are slightly visible). For an overview of the problem, see the attached screenshot. 

### System Preferences 
I noticed this problem on iPhone 8 with Google Chrome installed. IOS version - 14 (latest stable build).

##### UPD: Checked the same bug with Safari, it also exists there.

![FFB080C0-1CB4-4786-935F-1262526C0097](https://user-images.githubusercontent.com/59331246/125648353-50d57540-5a7e-441c-ade7-ffeb615f9681.png)

**Comment by Mirdukkk** [comment]
if someone is reading this, we did not drop the issue, it was sent to our discord server and we responded to it there. we'll fix it later.

**Comment by Pelfox** [comment]
Fixed by af206df.
